<a href="https://colab.research.google.com/github/ibrahimsesay/griddb/blob/master/Week2_Pre_Assignment_1_Matrix_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Problem 1. The Matrix product is calculated manually.

**QUESTION:**
$$
A=\begin{bmatrix} -1 & 2 & 3 \\ Four & -Five & 6 \\ 7 & 8 & -9 \end{bmatrix},
B=\begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}
$$

**SOLUTION**

**STEP 1:**
$$
\begin{bmatrix}
(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*-8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*9)&(7*1)+(8*-8)+(-9*-1)\\
\end{bmatrix},
$$


**STEP 2:**
$$
\begin{bmatrix}
(O+0+6)&(-2+4+27)&(-1-16-3)\\
(O+0+12)&(8-10+54)&(4+40-6)\\
(O+0-18)&(14+16-81)&(7-64+9)\\
\end{bmatrix},
$$

**FINAL ANSWER**
$$
\begin{pmatrix} 
6&29&-20\\
12&52&38\\
-18&-51&-46
\end{pmatrix}
$$


#  Problem.2 The Calculating by Numpy function.

In [ ]:
import   numpy   as  np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.matmul(a_ndarray,b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem Im 3.The Implementation of calculation of a certain element 

In [ ]:
ab = (a_ndarray[0][0]*b_ndarray[1][0])
ab

0

In [ ]:
ab = (a_ndarray[0][1]*b_ndarray[1][0])
ab

0

In [ ]:
ab = (a_ndarray[0][2]*b_ndarray[2][0])
ab

6

In [ ]:
sum_ab = (a_ndarray[0][0]*b_ndarray[0][0])+(a_ndarray[0][1]*b_ndarray[1][0])+(a_ndarray[0][2]*b_ndarray[2][0])
sum_ab

6

#  Problem 4. THE function that performs matrix multiplication

In [ ]:
def product_of_matrix(a, b):
    matrix_ab = np.empty([3,3])
    for row1 in range(a.shape[0]):
        for column1 in range(b.shape[1]):
            matrix_ab[row1][column1] = sum(a[row1, :]*b[:, column1])
    return matrix_ab
print(product_of_matrix(a_ndarray, b_ndarray))


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


#  Problem.5 Judge the input whose calculation is not define 

In [ ]:
d_ndarray = np.array([[-1, 2, 3],[4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7],[6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
        print("This matrices are not inline")

This matrices are not inline


# Problem 6.Transposition 

In [ ]:
z = d_ndarray.T
print(product_of_matrix(z, e_ndarray))


[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
